
# add tflint
# https://github.com/terraform-linters/tflint?tab=readme-ov-file#github-actions

# add terraform-docs?
# https://github.com/terraform-docs/terraform-docs/

# how to pass the .tfvars file for deployment? for all or one job?
#
#---------
  
# the problem i'm having with deployment using github actions
# https://chatgpt.com/c/6777f24d-29c4-800b-bebc-3f420b9626ee

# the actual issue i'm having... read up on
# https://duckduckgo.com/?q=Error+Code%09900023Message%09Specified+tenant+identifier+%27%7Btenant_id%7D%27+is+neither+a+valid+DNS+name%2C+nor+a+valid+external+domain.Remediation%09Application+error+-+the+login+request+was+malformed+and+could+not+be+matched+with+an+existing+authentication+endpoint+or+instance.&t=vivaldi&ia=web

# read up on 
# https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions
# https://github.com/Azure/login#login-with-a-service-principal-secret

name: terraform ci/cd

#


# add dependency caching
# see guide 73-75 \OneDrive - Redeploy AB\Documents\Knowledge Nexus\01 Project\Learnings\GitHub Actions\Udemy\V1\Section 5. Job Artifacts and Outputs

#

on:
  push:
    branches: [main, 'fix/**', 'feature/**']
  pull_request:
    branches: [main, 'fix/**', 'feature/**']

  workflow_dispatch:

  issues:
    types:
      - opened
      - edited
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  # Disabled until implemented nginx-storage-account-mess
  # log-issues:
  #   if: github.event_name == 'issues'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Output issue event data
  #       run: echo '${{ toJSON(github.event) }}'
  cicd:
    runs-on: ubuntu-latest
    environment: azure-deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          # necessary? remove if can solve storage account access
      - name: Assign Storage Blob Data Contributor to Service Principal
        run: |
          az role assignment create \
            --assignee ${{ secrets.AZURE_CLIENT_ID }} \
            --role "Storage Blob Data Contributor" \
            --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}
        continue-on-error: false

      - name: Assign Storage Account Contributor Role to SP
        run: |
          az role assignment create \
            --assignee ${{ secrets.AZURE_CLIENT_ID }} \
            --role "Storage Account Contributor" \
            --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg_project1/providers/Microsoft.Storage/storageAccounts/examplestoraccount5421
        continue-on-error: false

      - name: Export Azure env vars for Terraform
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

      - name: Discover runner's IP
        id: discover_ip
        run: echo "public_ip=$(curl -s ifconfig.me)" >> $GITHUB_OUTPUT
          
      - name: Print IP (for debugging)
        run: echo "My IP is ${{ steps.discover_ip.outputs.public_ip }}"
        


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~>1.9"
          
      - name: Terraform Init with debug
        run: terraform init -var-file='dev.tfvars'
        # i riktig miljö kommer det vara separerade repos för dev, test och prod
        # innebär att det undivker "problemet" med att .tfvars är hårdkodad i github pipen.
        #env:
          #TF_LOG: DEBUG

#
      - name: Terraform Format
        run: terraform fmt -recursive 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          # inte bra. impelmentera terraform som använder keyvaults och secrets med random module.
          # vid utskapande av vm, peka lösenord på secret id.
          TF_VAR_admin_username: ${{ secrets.TF_VAR_admin_username }}
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }}
        run: terraform plan -input=false -var "runner_public_ip=${{ steps.discover_ip.outputs.public_ip }}" -out=plan.out  -var-file='dev.tfvars'

      - name: Terraform Apply
        env:
          # inte bra. impelmentera terraform som använder keyvaults och secrets med random module.
          # vid utskapande av vm, peka lösenord på secret id.
          TF_VAR_admin_username: ${{ secrets.TF_VAR_admin_username }} # for key vault 
          TF_VAR_admin_password: ${{ secrets.TF_VAR_admin_password }} # for key vault
        run: terraform apply -auto-approve -input=false -var "runner_public_ip=${{ steps.discover_ip.outputs.public_ip }}" -var-file='dev.tfvars'
        



      # integrate linting as next workflow-step. check out the upload/artefacts..      #
      # - name: Upload Terraform Plan
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: tf-plan
      #     path: plan.out
      #
      # samt... logik "om pull request inte är typ "fix-" kommer den faila och outputta "ditt namn är fel".
      # 